#operadores lógicos y de comparación
print()
print("***operadores lógicos***")
print()
es_estudiante = True
print("es estudiante lo definí en True:",es_estudiante)
print()
trabaja = False
print("trabaja lo definí en False:",trabaja)
print()
logico_and = es_estudiante and trabaja
print("lógico and en donde le digo que si es estudiante y trabaja:",logico_and)
print()
logico_or = es_estudiante or trabaja
print("lógico or en donde le digo que si es estudiante ó trabaja:",logico_or)
print()
logico_not1 = not es_estudiante
print("lógico not en donde le digo que no es estudiante:",logico_not1)
print()
logico_not2 = not trabaja
print("lógico not en donde le digo que no trabaja:",logico_not2)
print()
print("***operadores de comparación***")
print()
print("de igualdad: == donde le digo que una variable o dato es igual que otra, ejemplo: 5==5:", 5==5)
print()
print("de igualdad: == donde le digo que una variable o dato es igual que otra, ejemplo: 5==7:", 5==7)
print()
print("distinto de: != dónde le digo que una variable o dato es distinta de otra, ejemplo: 5!=5:", 5!=5)
print()
print("distinto de: != dónde le digo que una variable o dato es distinta de otra, ejemplo: 6!=5:", 6!=5)
print()
print("mayor qué: > donde le digo que una variable o dato es mayor que otra, ejemplo: 5>4:", 5>4)
print()
print("mayor qué: > donde le digo que una variable o dato es mayor que otra, ejemplo: 4>5:", 4>5)
print()
print("menor qué: < donde le digo que una variable o dato es menor que otra, ejemplo: 2<4:", 2<4)
print()
print("menor qué: < donde le digo que una variable o dato es menor que otra, ejemplo: 5<4:", 5<4)
print()
print("mayor o igual qué: >= donde le digo que una variable o dato es mayor o igual que otra, ejemplo: 5>=5:", 5>=5)
print()
print("mayor o igual qué: >= donde le digo que una variable o dato es mayor o igual que otra, ejemplo: 4>=5:", 4>=5)
print()
print("menor o igual qué: <= donde le digo que una variable o dato es menor o igual que otra, ejemplo: 4<=4:", 4<=4)
print()
print("menor o igual qué: <= donde le digo que una variable o dato es menor o igual que otra, ejemplo: 5<=4:", 5<=4)
print()