#suma
print("Suma 5+6 es igual a:",5+6)
#resta
print("Resta de 4-7 es igual a:",4-7)
print("Resta de 46-37 es igual a:",46-37)
#multiplicación
print("Multiplicación de 4*7 es igual a:",4*7)
#división con decimales
print()
print("*******división para obtener un resultado con decimales*******")
print("La división con decimales es con un solo /")
print("entonces la división es así, 5/5 es igual a:",5/5)
print("***otro ejemplo para obtener un resultado con decimales***")
print("entonces la división es así, 21/5 es igual a:",21/5)
print()
print("*******división para obtener un resultado sin decimales*******")
print("La división sin decimales es con dos //")
print("entonces la división es así, 5//5 es igual a:",5//5)
print("***otro ejemplo***")
print("entonces la división es así, 21//5 es igual a:",21//5)
print()
print("el resto de una division se obtiene con el %")
print("entonces la operación sería así 21%5 es igual a:",21%5)
print()
print("La potencia de un número se obtiene con doble ** entonces el resultado de 2**2 es igual a:",2**2)
print()
print("Debemos tener en cuenta que python respeta las reglas matemáticas, por lo que él siempre resuelve por jerarquía y un ejemplo de ello es el siguiente")
print("5+5*2 es igual a:",5+5*2, "porque como dijimos antes respeta el orden jerarquico y primero se soluciona la multiplicación y luego hace la suma")
print()
print("Para obtener la raíz cuadrada se importa el metodo math y se obtiene de la siguiente manera")
print("import math")
import math
print("math.sqrt(9) es igual a:",math.sqrt(9))
print("math.sqrt(11.11) es igual a:",math.sqrt(11.11))